theme: jekyll-theme-cayman
encoding: utf-8
title: tippy
author: tippy
email: tippy3@users.noreply.github.com
description: "新米SRE"
exclude:
  - README.md
  - index_old.md
  - vendor
  - Gemfile
  - Gemfile.lock
